// File Variables

// 基本
@protocol = http
@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@baseUrl = {{protocol}}://{{host}}/api
@apiV = /v1
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@boundary = ----MyBoundary
// ENVファイルからの読み込み
@jwt = {{$dotenv AUTH_DATA_TOKEN}}
// 変数
@hoge_uuid = 1db31e56-5b62-4c98-b951-997e49b401e1

// Requests

// envデータ送信（MQTTに置き換わる予定）
POST {{baseUrl}}/env HTTP/1.1
Content-Type: application/json

{
    "temperatureSht": 24.5,
    "humidity": 60.0,
    "temperatureQmp": 22.8,
    "pressure": 1013.2
}

###