trailingComma: "all" # 末尾カンマ
tabWidth: 2 # タブ幅
useTabs: false # タブではなくスペースを利用
quoteProps: "as-needed" # プロパティ名に引用符が必要な場合のみ囲む
bracketSpacing: true # 括弧内にスペースを入れる
bracketSameLine: false # タグの閉じ角括弧を同一行にするか、falseだとスコープの波括弧みたいな見た目になる
arrowParens: always # アロー関数で引数を常に括弧で囲む
semi: true # 行末セミコロン
singleQuote: true # 二重引用符の代わりに一重引用符を強制するかどうか
jsxSingleQuote: true # JSXで二重引用符の代わりに一重引用符を強制するかどうか
printWidth: 100 # 折り返し幅、デフォルトは80らしいが少し広めに取りたい
embeddedLanguageFormatting: auto # 組み込み言語の見た目をフォーマットするかどうか
vueIndentScriptAndStyle: true # HTML, Vue, JSXの<script>or<style>タグをインデントするかどうか、インデントレベルを犠牲にして可読性を上げる
htmlWhitespaceSensitivity: css # HTML系で意味のある空白と意味のない空白の扱い
singleAttributePerLine: false # HTMLタグの属性をすべて改行するかどうか、長いと判断されたら自動折り返しにしておく
endOfLine: lf # 改行コードを指定